### ISSUE TITLE
Error while running on windows

### ISSUE THREAD

**Issue by acubenchik** [swarajban/npm-cache#7] opened 2015-05-29 14:11 UTC
I'm trying to run npm-cache install npm from windows shell and get the following:
[npm-cache] [INFO] [npm] installed npm dependencies, now archiving
[npm-cache] [INFO] [npm] archiving dependencies from node_modules
tar (child): Cannot execute remote shell: No such file or directory
tar (child): C\:\\Users\\username\\.package_cache\\18c7544ea9d5afdef076583351ae2
7a2.tar.gz: Cannot open: I/O error
tar (child): Error is not recoverable: exiting now
stdout: Invalid argument

gzip: [npm-cache] [ERROR] [npm] error tar-ing node_modules
rm: no such file or directory: C:\Users\username\.package_cache\18c7544ea9d5afde
f076583351ae27a2.tar.gz

[npm-cache] [ERROR] error installing dependencies

The same works fine on linux.

npm-cache -v 0.3.0

**Comment by swarajban** [comment] 2015-06-02 22:05
Ya this is a dupe of #4 Closing. :( Sorry have not had time to work on these fixes yet

**Closed by swarajban** 2015-06-02 22:05 UTC
